<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Week 3 Quiz</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Week 3 Quiz</h1>

<p>Question 1</p>

<p>The American Community Survey distributes downloadable data about United States communities. Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv">https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv</a> </p>

<p>and load the data into R. The code book, describing the variable names is here: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf">https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf</a> </p>

<p>Create a logical vector that identifies the households on greater than 10 acres who sold more than $10,000 worth of agriculture products. Assign that logical vector to the variable agricultureLogical. Apply the which() function like this to identify the rows of the data frame where the logical vector is TRUE. which(agricultureLogical) What are the first 3 values that result?
236, 238, 262
59, 460, 474
125, 238,262
153 ,236, 388</p>

<pre><code class="r">if (!file.exists(&quot;dataTest&quot;)) {
    dir.create(&quot;dataTest&quot;)
}

dataOrigin &lt;- &quot;https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv&quot;

destfile &lt;- &quot;./dataTest/dataQ1.csv&quot;

if (!file.exists(destfile)) {
    getwd()
    download.file(dataOrigin, destfile, method = &quot;curl&quot;)
}

datos &lt;- read.csv(destfile)

head(datos)
</code></pre>

<pre><code>##   RT SERIALNO DIVISION PUMA REGION ST  ADJUST WGTP NP TYPE ACR AGS BDS BLD
## 1  H      186        8  700      4 16 1015675   89  4    1   1  NA   4   2
## 2  H      306        8  700      4 16 1015675  310  1    1  NA  NA   1   7
## 3  H      395        8  100      4 16 1015675  106  2    1   1  NA   3   2
## 4  H      506        8  700      4 16 1015675  240  4    1   1  NA   4   2
## 5  H      835        8  800      4 16 1015675  118  4    1   2   1   5   2
## 6  H      989        8  700      4 16 1015675  115  4    1   1  NA   3   2
##   BUS CONP ELEP FS FULP GASP HFL INSP KIT MHP MRGI MRGP MRGT MRGX PLM RMS
## 1   2   NA  180  0    2    3   3  600   1  NA    1 1300    1    1   1   9
## 2  NA   NA   60  0    2    3   3   NA   1  NA   NA   NA   NA   NA   1   2
## 3   2   NA   70  0    2   30   1  200   1  NA   NA   NA   NA    3   1   7
## 4   2   NA   40  0    2   80   1  200   1  NA    1  860    1    1   1   6
## 5   2   NA  250  0    2    3   3  700   1  NA    1 1900    1    1   1   7
## 6   2   NA  130  0    2    3   3  250   1  NA    1  700    1    1   1   6
##   RNTM RNTP SMP TEL TEN VACS VAL VEH WATP YBL FES  FINCP FPARC GRNTP GRPIP
## 1   NA   NA  NA   1   1   NA  17   3  840   5   2 105600     2    NA    NA
## 2    2  600  NA   1   3   NA  NA   1    1   3  NA     NA    NA   660    23
## 3   NA   NA  NA   1   2   NA  18   2   50   5   7   9400     2    NA    NA
## 4   NA   NA 400   1   1   NA  19   3  500   2   1  66000     1    NA    NA
## 5   NA   NA 650   1   1   NA  20   5    2   3   1  93000     2    NA    NA
## 6   NA   NA 400   1   1   NA  15   2 1200   5   2  61000     1    NA    NA
##   HHL HHT  HINCP HUGCL HUPAC HUPAOC HUPARC LNGI MV NOC NPF NPP NR NRC
## 1   1   1 105600     0     2      2      2    1  4   2   4   0  0   2
## 2   1   4  34000     0     4      4      4    1  3   0  NA   0  0   0
## 3   1   3   9400     0     2      2      2    1  2   1   2   0  0   1
## 4   1   1  66000     0     1      1      1    1  3   2   4   0  0   2
## 5   1   1  93000     0     2      2      2    1  1   1   4   0  0   1
## 6   1   1  61000     0     1      1      1    1  4   2   4   0  0   2
##   OCPIP PARTNER PSF R18 R60 R65 RESMODE SMOCP SMX SRNT SVAL TAXP WIF
## 1    18       0   0   1   0   0       1  1550   3    0    1   24   3
## 2    NA       0   0   0   0   0       2    NA  NA    1    0   NA  NA
## 3    23       0   0   1   0   0       1   179  NA    0    1   16   1
## 4    26       0   0   1   0   0       2  1422   1    0    1   31   2
## 5    36       0   0   1   0   0       1  2800   1    0    1   25   3
## 6    26       0   0   1   0   0       2  1330   2    0    1    7   1
##   WKEXREL WORKSTAT FACRP FAGSP FBDSP FBLDP FBUSP FCONP FELEP FFSP FFULP
## 1       2        3     0     0     0     0     0     0     0    0     0
## 2      NA       NA     0     0     0     0     0     0     0    0     0
## 3      13       13     0     0     0     0     0     0     0    0     0
## 4       2        1     0     0     0     0     0     0     0    0     0
## 5       1        1     0     0     0     0     0     0     0    0     0
## 6       7        3     0     0     0     0     0     0     0    0     0
##   FGASP FHFLP FINSP FKITP FMHP FMRGIP FMRGP FMRGTP FMRGXP FMVYP FPLMP
## 1     0     0     0     0    0      0     0      0      0     0     0
## 2     0     0     0     0    0      0     0      0      0     0     0
## 3     0     0     0     0    0      0     0      0      0     0     0
## 4     0     0     0     0    0      0     0      0      0     0     0
## 5     0     0     0     0    0      0     0      0      0     0     0
## 6     0     0     1     0    0      0     0      0      0     0     0
##   FRMSP FRNTMP FRNTP FSMP FSMXHP FSMXSP FTAXP FTELP FTENP FVACSP FVALP
## 1     0      0     0    0      0      0     0     0     0      0     0
## 2     0      0     0    0      0      0     0     0     0      0     0
## 3     0      0     0    0      0      0     0     0     0      0     0
## 4     0      0     0    0      0      0     0     0     0      0     0
## 5     0      0     0    0      0      0     0     0     0      0     0
## 6     0      0     0    0      0      0     1     0     0      0     0
##   FVEHP FWATP FYBLP wgtp1 wgtp2 wgtp3 wgtp4 wgtp5 wgtp6 wgtp7 wgtp8 wgtp9
## 1     0     0     0    87    28   156    95    26    25    95    93    93
## 2     0     0     1   539   363   293   422   566   289    87   242   453
## 3     0     0     0   187    35   184   178    83    95    31    32   177
## 4     0     0     0   232   406   234   270   249   242   406   249   287
## 5     0     0     0   107   194   129    41   156   174    47   113   101
## 6     0     1     0   191   197   127   115   115   107   119    34    32
##   wgtp10 wgtp11 wgtp12 wgtp13 wgtp14 wgtp15 wgtp16 wgtp17 wgtp18 wgtp19
## 1     91     87    166     90     25    153     89    148     82     25
## 2    453    334    358    414    102    281     99    108    278    131
## 3    118    110    114    184    107     95    115     33    118    120
## 4     67     72    413    399     77    245    424     67     63    226
## 5     33    115     52    113     95    135    206    100    185    135
## 6     30    123    199    117     33    109    117     31    115    201
##   wgtp20 wgtp21 wgtp22 wgtp23 wgtp24 wgtp25 wgtp26 wgtp27 wgtp28 wgtp29
## 1    180     90     24    140     92     25     27     86     84     87
## 2    407    447    264    352    238    390    336    122    374    482
## 3     37    184     35    176    176    110    103     29     30    197
## 4    254    238     69    238    255    239    248     69    234    247
## 5    279    116     33    105    244     38     30    230    123    123
## 6    190    184    198    113    109    117    111    110     33     37
##   wgtp30 wgtp31 wgtp32 wgtp33 wgtp34 wgtp35 wgtp36 wgtp37 wgtp38 wgtp39
## 1     93     90    149     91     28    143     81    144     95     27
## 2    468    335    251    613    104    284    116     91    326    102
## 3    127     92    118    177     99     99    109     34    100    105
## 4    437    423     74     61    401    267     72    388    335    229
## 5    243    120    238     98     90    107     44    122     32    127
## 6     36    110    183    114     35    134    119     32    121    188
##   wgtp40 wgtp41 wgtp42 wgtp43 wgtp44 wgtp45 wgtp46 wgtp47 wgtp48 wgtp49
## 1     22     90    171     27     83    153    148     92     91     91
## 2    361    107    253    321    289     96    343    564    274    118
## 3     33    173     36    168    175     99    103     30     35    155
## 4    236    239     65    259    247    230    225     82    220    233
## 5    195    116     36    135    237     33     33    249    102     84
## 6     33     34     32    109    115    115    112    119    192    186
##   wgtp50 wgtp51 wgtp52 wgtp53 wgtp54 wgtp55 wgtp56 wgtp57 wgtp58 wgtp59
## 1     93     90     26     94    142     24     91     29     84    148
## 2    118    321    261    130    463    294    479    391    307    476
## 3    102     95    107    185    120    114    113     36    115    103
## 4    419    390     69     74    391    276     70    422    409    223
## 5    224    119    250    119    125    126     32    112     33    131
## 6    213    106     34    124    179    106    107    190    112     34
##   wgtp60 wgtp61 wgtp62 wgtp63 wgtp64 wgtp65 wgtp66 wgtp67 wgtp68 wgtp69
## 1     30     93    143     24     88    147    145     91     83     83
## 2    283    116    353    323    374    106    236    380    313     90
## 3     29    183     35    179    169     95    110     28     34    233
## 4    245    269    488    221    250    247    240    415    234    219
## 5     45    101    165    125     41    191    195     49    119     92
## 6     35     32     34    119    123    122    121    123    196    196
##   wgtp70 wgtp71 wgtp72 wgtp73 wgtp74 wgtp75 wgtp76 wgtp77 wgtp78 wgtp79
## 1     86     81     27     93    151     28     79     25    101    157
## 2     94    292    401     81    494    346    496    615    286    454
## 3     97    123    119    168    107     95    101     30    124    106
## 4     66     68    359    385     71    234    421     76     77    242
## 5     44    127     36    119    121    116    209     97    176    144
## 6    207    120     34    109    199    116    110    211    120     31
##   wgtp80
## 1    129
## 2    260
## 3     31
## 4    231
## 5     38
## 6    189
</code></pre>

<p>De acuerdo con la documentacion  la primera condicion implica que la variable (ACR) tiene que tener un valor de 3 y la variable AGS un valor de 6 </p>

<pre><code class="r">agricultureLogical &lt;- ((datos$ACR == 3) &amp; (datos$AGS == 6))
head(agricultureLogical)
</code></pre>

<pre><code>## [1] FALSE    NA FALSE FALSE FALSE FALSE
</code></pre>

<pre><code class="r">which(agricultureLogical)
</code></pre>

<pre><code>##  [1]  125  238  262  470  555  568  608  643  787  808  824  849  952  955
## [15] 1033 1265 1275 1315 1388 1607 1629 1651 1856 1919 2101 2194 2403 2443
## [29] 2539 2580 2655 2680 2740 2838 2965 3131 3133 3163 3291 3370 3402 3585
## [43] 3652 3852 3862 3912 4023 4045 4107 4113 4117 4185 4198 4310 4343 4354
## [57] 4448 4453 4461 4718 4817 4835 4910 5140 5199 5236 5326 5417 5531 5574
## [71] 5894 6033 6044 6089 6275 6376 6420
</code></pre>

<h2>Question 2</h2>

<p>Using the jpeg package read in the following picture of your instructor into R </p>

<p><a href="https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg">https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg</a> </p>

<p>Use the parameter native=TRUE. What are the 30th and 80th quantiles of the resulting data? (some Linux systems may produce an answer 638 different for the 30th quantile)
-10904118 -10575416
10904118 -594524
-15259150 -10575416
-15259150 -594524 </p>

<p>empezamos por cargar el package y descargar el archi</p>

<pre><code class="r">if (!file.exists(&quot;dataTest&quot;)) {
    dir.create(&quot;dataTest&quot;)
}

dataOrigin &lt;- &quot;https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg&quot;

destfile &lt;- &quot;./dataTest/dataQ2.jpg&quot;

if (!file.exists(destfile)) {
    getwd()
    download.file(dataOrigin, destfile, method = &quot;curl&quot;)
}

library(jpeg)
image &lt;- readJPEG(destfile, native = TRUE)
</code></pre>

<p>ahora que tenemos los datos es tan facil como </p>

<pre><code class="r">quantile(image, probs = c(0.3, 0.8))
</code></pre>

<pre><code>##       30%       80% 
## -15259150 -10575416
</code></pre>

<h2>Question 3</h2>

<p>Load the Gross Domestic Product data for the 190 ranked countries in this data set: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv">https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv</a> </p>

<p>Load the educational data from this data set: </p>

<p><a href="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv">https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv</a> </p>

<p>Match the data based on the country shortcode. How many of the IDs match? Sort the data frame in descending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame? </p>

<p>Original data sources: 
<a href="http://data.worldbank.org/data-catalog/GDP-ranking-table">http://data.worldbank.org/data-catalog/GDP-ranking-table</a> 
<a href="http://data.worldbank.org/data-catalog/ed-stats">http://data.worldbank.org/data-catalog/ed-stats</a>
190, Spain
234, Spain
189, St. Kitts and Nevis
189, Spain
190, St. Kitts and Nevis
234, St. Kitts and Nevis</p>

<p>En primer lugar descargamos los archivos y los cargamos en DF</p>

<pre><code class="r">if (!file.exists(&quot;dataTest&quot;)) {
    dir.create(&quot;dataTest&quot;)
}

dataOriginGDP &lt;- &quot;https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv &quot;

destfileGDP &lt;- &quot;./dataTest/GDP.csv&quot;

if (!file.exists(destfileGDP)) {
    getwd()
    download.file(dataOriginGDP, destfileGDP, method = &quot;curl&quot;)
}


dataOriginEDU &lt;- &quot;https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv  &quot;

destfileEDU &lt;- &quot;./dataTest/EDU.csv&quot;

if (!file.exists(destfileEDU)) {
    getwd()
    download.file(dataOriginEDU, destfileEDU, method = &quot;curl&quot;)
}

dataGDP &lt;- read.csv(destfileGDP, na.strings = c(&quot;&quot;, &quot;NA&quot;), skip = 4, nrows = 190)
dataEDU &lt;- read.csv(destfileEDU, na.strings = c(&quot;&quot;, &quot;NA&quot;))
head(dataGDP)
</code></pre>

<pre><code>##     X X.1 X.2            X.3          X.4  X.5 X.6 X.7 X.8 X.9
## 1 USA   1  NA  United States  16,244,600  &lt;NA&gt;  NA  NA  NA  NA
## 2 CHN   2  NA          China   8,227,103  &lt;NA&gt;  NA  NA  NA  NA
## 3 JPN   3  NA          Japan   5,959,718  &lt;NA&gt;  NA  NA  NA  NA
## 4 DEU   4  NA        Germany   3,428,131  &lt;NA&gt;  NA  NA  NA  NA
## 5 FRA   5  NA         France   2,612,878  &lt;NA&gt;  NA  NA  NA  NA
## 6 GBR   6  NA United Kingdom   2,471,784  &lt;NA&gt;  NA  NA  NA  NA
</code></pre>

<pre><code class="r">head(dataEDU)
</code></pre>

<pre><code>##   CountryCode                    Long.Name         Income.Group
## 1         ABW                        Aruba High income: nonOECD
## 2         ADO      Principality of Andorra High income: nonOECD
## 3         AFG Islamic State of Afghanistan           Low income
## 4         AGO  People&#39;s Republic of Angola  Lower middle income
## 5         ALB          Republic of Albania  Upper middle income
## 6         ARE         United Arab Emirates High income: nonOECD
##                       Region Lending.category Other.groups  Currency.Unit
## 1  Latin America &amp; Caribbean             &lt;NA&gt;         &lt;NA&gt;  Aruban florin
## 2      Europe &amp; Central Asia             &lt;NA&gt;         &lt;NA&gt;           Euro
## 3                 South Asia              IDA         HIPC Afghan afghani
## 4         Sub-Saharan Africa              IDA         &lt;NA&gt; Angolan kwanza
## 5      Europe &amp; Central Asia             IBRD         &lt;NA&gt;   Albanian lek
## 6 Middle East &amp; North Africa             &lt;NA&gt;         &lt;NA&gt;  U.A.E. dirham
##   Latest.population.census  Latest.household.survey
## 1                     2000                     &lt;NA&gt;
## 2           Register based                     &lt;NA&gt;
## 3                     1979               MICS, 2003
## 4                     1970 MICS, 2001, MIS, 2006/07
## 5                     2001               MICS, 2005
## 6                     2005                     &lt;NA&gt;
##                                                                 Special.Notes
## 1                                                                        &lt;NA&gt;
## 2                                                                        &lt;NA&gt;
## 3 Fiscal year end: March 20; reporting period for national accounts data: FY.
## 4                                                                        &lt;NA&gt;
## 5                                                                        &lt;NA&gt;
## 6                                                                        &lt;NA&gt;
##   National.accounts.base.year National.accounts.reference.year
## 1                        1995                               NA
## 2                        &lt;NA&gt;                               NA
## 3                   2002/2003                               NA
## 4                        1997                               NA
## 5                        &lt;NA&gt;                             1996
## 6                        1995                               NA
##   System.of.National.Accounts SNA.price.valuation
## 1                          NA                &lt;NA&gt;
## 2                          NA                &lt;NA&gt;
## 3                          NA                 VAB
## 4                          NA                 VAP
## 5                        1993                 VAB
## 6                          NA                 VAB
##   Alternative.conversion.factor PPP.survey.year
## 1                          &lt;NA&gt;              NA
## 2                          &lt;NA&gt;              NA
## 3                          &lt;NA&gt;              NA
## 4                       1991-96            2005
## 5                          &lt;NA&gt;            2005
## 6                          &lt;NA&gt;              NA
##   Balance.of.Payments.Manual.in.use External.debt.Reporting.status
## 1                              &lt;NA&gt;                           &lt;NA&gt;
## 2                              &lt;NA&gt;                           &lt;NA&gt;
## 3                              &lt;NA&gt;                         Actual
## 4                              BPM5                         Actual
## 5                              BPM5                         Actual
## 6                              BPM4                           &lt;NA&gt;
##   System.of.trade Government.Accounting.concept
## 1         Special                          &lt;NA&gt;
## 2         General                          &lt;NA&gt;
## 3         General                  Consolidated
## 4         Special                          &lt;NA&gt;
## 5         General                  Consolidated
## 6         General                  Consolidated
##   IMF.data.dissemination.standard
## 1                            &lt;NA&gt;
## 2                            &lt;NA&gt;
## 3                            GDDS
## 4                            GDDS
## 5                            GDDS
## 6                            GDDS
##   Source.of.most.recent.Income.and.expenditure.data
## 1                                              &lt;NA&gt;
## 2                                              &lt;NA&gt;
## 3                                              &lt;NA&gt;
## 4                                         IHS, 2000
## 5                                        LSMS, 2005
## 6                                              &lt;NA&gt;
##   Vital.registration.complete Latest.agricultural.census
## 1                        &lt;NA&gt;                       &lt;NA&gt;
## 2                         Yes                       &lt;NA&gt;
## 3                        &lt;NA&gt;                       &lt;NA&gt;
## 4                        &lt;NA&gt;                    1964-65
## 5                         Yes                       1998
## 6                        &lt;NA&gt;                       1998
##   Latest.industrial.data Latest.trade.data Latest.water.withdrawal.data
## 1                     NA              2008                           NA
## 2                     NA              2006                           NA
## 3                     NA              2008                         2000
## 4                     NA              1991                         2000
## 5                   2005              2008                         2000
## 6                     NA              2008                         2005
##   X2.alpha.code WB.2.code           Table.Name           Short.Name
## 1            AW        AW                Aruba                Aruba
## 2            AD        AD              Andorra              Andorra
## 3            AF        AF          Afghanistan          Afghanistan
## 4            AO        AO               Angola               Angola
## 5            AL        AL              Albania              Albania
## 6            AE        AE United Arab Emirates United Arab Emirates
</code></pre>

<pre><code class="r"># vamos a retocar un poquito los nombres de dataGDP que asi son feos
names(dataGDP)[1] &lt;- &quot;ShortCode&quot;
names(dataGDP)[2] &lt;- &quot;GDPRank&quot;
</code></pre>

<p>Por inspeccion vemos que el codigo de archivo es en dataEdu, &ldquo;CountryCode&rdquo;, mientras que en GDP es la primera columna que es &ldquo;ShortCode&rdquo;  asi que va a tocar hacerlo con merge Ojo, que solo valian los ranked</p>

<pre><code class="r">dataMERG &lt;- merge(dataEDU, dataGDP, by.x = &quot;CountryCode&quot;, by.y = &quot;ShortCode&quot;)
dim(dataMERG)
</code></pre>

<pre><code>## [1] 189  40
</code></pre>

<p>el numero que coinciden es 189</p>

<p>Para la segunda parte hay que colocarlos por la columna GDPRank, pero antes hay que convertirla en numerica que si no la liamos </p>

<pre><code class="r">dataMERG$GDPRank &lt;- as.numeric(dataMERG$GDPRank)

library(plyr)
dataMERGORD &lt;- arrange(dataMERG, desc(GDPRank))
dataMERGORD[13, 2]
</code></pre>

<pre><code>## [1] St. Kitts and Nevis
## 234 Levels: American Samoa Antigua and Barbuda ... World
</code></pre>

<p>y por supuesto sale ST kits  </p>

<p>DataMERG nos va a seguir haciendo falta para las proximas </p>

<h2>Question 4</h2>

<p>What is the average GDP ranking for the &ldquo;High income: OECD&rdquo; and &ldquo;High income: nonOECD&rdquo; group? </p>

<p>hay que hacerlo por income group </p>

<pre><code class="r">sapply(split(dataMERG$GDPRank, dataMERG$Income.Group), mean)
</code></pre>

<pre><code>##    High income: OECD High income: nonOECD           Low income 
##                32.97                91.91               133.73 
##  Lower middle income  Upper middle income 
##               107.70                92.13
</code></pre>

<h2>Question 5</h2>

<p>Cut the GDP ranking into 5 separate quantile groups. Make a table versus Income.Group. How many countries are Lower middle income but among the 38 nations with highest GDP?</p>

<p>Metemos los grupos en una nueva variable y hacemos la tabla</p>

<pre><code class="r">dataMERG$GDPQ &lt;- cut(dataMERG$GDPRank, 5)
table(dataMERG$GDPQ, dataMERG$Income.Group)
</code></pre>

<pre><code>##               
##                High income: OECD High income: nonOECD Low income
##   (0.811,38.8]                18                    4          0
##   (38.8,76.6]                 10                    5          1
##   (76.6,114]                   1                    8          9
##   (114,152]                    1                    4         16
##   (152,190]                    0                    2         11
##               
##                Lower middle income Upper middle income
##   (0.811,38.8]                   5                  11
##   (38.8,76.6]                   13                   9
##   (76.6,114]                    12                   8
##   (114,152]                      8                   8
##   (152,190]                     16                   9
</code></pre>

<p>La respuesta se saca por inspeccion del resultado</p>

</body>

</html>

